### PR TITLE
rockbox_psgroove

### PR DESCRIPTION
**Pull request by 0xFelix**
I updated PL3 and added support for FW2.70 and FW3.41 Kiosk :)

### CODE REVIEW

**Comment by shuffle2** [comment]
latest pl3 actually works? Last time I tried, it didn't...maybe I had just tried when a bug was introduced or something :)

**Comment by 0xFelix** [comment]
yes it works :)

**Comment by 0xFelix** [comment]
are you sure you have the latest pl3?! the pl3 version that i used as submodule generated all needed files for me...

**Comment by shuffle2** [comment]
Ah I see...the merge did not actually update pl3 locally :)
Fixed now.

**Pull request merged**
